### ISSUE TITLE
Récupération du fichier Mars_resolver.json

### ISSUE THREAD

**Issue by KDassas** [SITools2/MIZAR#18]
Le fichier n'est plus disponible au même en droit qu'avant. 
L'IAS aimerait récupérer ce fichier localement.

**Comment by malapert** [comment]
Lorsque l'on utilise la branche dev de MIZAR, il est disponible dans ce répertoire : https://github.com/SITools2/MIZAR/blob/dev/src/mizar_lite/data/mars_resolver.json
